# Generated by Django 4.1.7 on 2023-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('certtificate', models.ImageField(upload_to='certifates')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skillImage',
        ),
    ]
