# Generated by Django 4.1.7 on 2023-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_achievement_remove_skill_skillimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='certtificate',
        ),
        migrations.AddField(
            model_name='achievement',
            name='certificate',
            field=models.ImageField(null=True, upload_to='certificate'),
        ),
    ]
