# Generated by Django 4.1.7 on 2023-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_achievement_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('project', models.ImageField(null=True, upload_to='project')),
                ('url', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
